# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AttackType(str, Enum):
    """
    The type of an attack
    """

    """
    allowed enum values
    """
    UNDEFINED = 'Undefined'
    BRUTEFORCESUBDOMAINS = 'BruteforceSubdomains'
    TCPPORTSCAN = 'TcpPortScan'
    QUERYCERTIFICATETRANSPARENCY = 'QueryCertificateTransparency'
    QUERYUNHASHED = 'QueryUnhashed'
    HOSTALIVE = 'HostAlive'
    SERVICEDETECTION = 'ServiceDetection'
    DNSRESOLUTION = 'DnsResolution'
    UDPPORTSCAN = 'UdpPortScan'
    FORCEDBROWSING = 'ForcedBrowsing'
    OSDETECTION = 'OSDetection'
    VERSIONDETECTION = 'VersionDetection'
    ANTIPORTSCANNINGDETECTION = 'AntiPortScanningDetection'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AttackType from a JSON string"""
        return cls(json.loads(json_str))


