# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, field_validator
from kraken_sdk.models.query_one_of import QueryOneOf
from kraken_sdk.models.query_one_of1 import QueryOneOf1
from kraken_sdk.models.query_one_of2 import QueryOneOf2
from kraken_sdk.models.query_one_of3 import QueryOneOf3
from kraken_sdk.models.query_one_of4 import QueryOneOf4
from kraken_sdk.models.query_one_of5 import QueryOneOf5
from kraken_sdk.models.query_one_of6 import QueryOneOf6
from kraken_sdk.models.query_one_of7 import QueryOneOf7
from kraken_sdk.models.query_one_of8 import QueryOneOf8
from kraken_sdk.models.query_one_of9 import QueryOneOf9
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

QUERY_ONE_OF_SCHEMAS = ["QueryOneOf", "QueryOneOf1", "QueryOneOf2", "QueryOneOf3", "QueryOneOf4", "QueryOneOf5", "QueryOneOf6", "QueryOneOf7", "QueryOneOf8", "QueryOneOf9"]

class Query(BaseModel):
    """
    A query for dehashed
    """
    # data type: QueryOneOf
    oneof_schema_1_validator: Optional[QueryOneOf] = None
    # data type: QueryOneOf1
    oneof_schema_2_validator: Optional[QueryOneOf1] = None
    # data type: QueryOneOf2
    oneof_schema_3_validator: Optional[QueryOneOf2] = None
    # data type: QueryOneOf3
    oneof_schema_4_validator: Optional[QueryOneOf3] = None
    # data type: QueryOneOf4
    oneof_schema_5_validator: Optional[QueryOneOf4] = None
    # data type: QueryOneOf5
    oneof_schema_6_validator: Optional[QueryOneOf5] = None
    # data type: QueryOneOf6
    oneof_schema_7_validator: Optional[QueryOneOf6] = None
    # data type: QueryOneOf7
    oneof_schema_8_validator: Optional[QueryOneOf7] = None
    # data type: QueryOneOf8
    oneof_schema_9_validator: Optional[QueryOneOf8] = None
    # data type: QueryOneOf9
    oneof_schema_10_validator: Optional[QueryOneOf9] = None
    actual_instance: Optional[Union[QueryOneOf, QueryOneOf1, QueryOneOf2, QueryOneOf3, QueryOneOf4, QueryOneOf5, QueryOneOf6, QueryOneOf7, QueryOneOf8, QueryOneOf9]] = None
    one_of_schemas: List[str] = Literal["QueryOneOf", "QueryOneOf1", "QueryOneOf2", "QueryOneOf3", "QueryOneOf4", "QueryOneOf5", "QueryOneOf6", "QueryOneOf7", "QueryOneOf8", "QueryOneOf9"]

    model_config = {
        "validate_assignment": True
    }


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Query.model_construct()
        error_messages = []
        match = 0
        # validate data type: QueryOneOf
        if not isinstance(v, QueryOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf`")
        else:
            match += 1
        # validate data type: QueryOneOf1
        if not isinstance(v, QueryOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf1`")
        else:
            match += 1
        # validate data type: QueryOneOf2
        if not isinstance(v, QueryOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf2`")
        else:
            match += 1
        # validate data type: QueryOneOf3
        if not isinstance(v, QueryOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf3`")
        else:
            match += 1
        # validate data type: QueryOneOf4
        if not isinstance(v, QueryOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf4`")
        else:
            match += 1
        # validate data type: QueryOneOf5
        if not isinstance(v, QueryOneOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf5`")
        else:
            match += 1
        # validate data type: QueryOneOf6
        if not isinstance(v, QueryOneOf6):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf6`")
        else:
            match += 1
        # validate data type: QueryOneOf7
        if not isinstance(v, QueryOneOf7):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf7`")
        else:
            match += 1
        # validate data type: QueryOneOf8
        if not isinstance(v, QueryOneOf8):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf8`")
        else:
            match += 1
        # validate data type: QueryOneOf9
        if not isinstance(v, QueryOneOf9):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QueryOneOf9`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Query with oneOf schemas: QueryOneOf, QueryOneOf1, QueryOneOf2, QueryOneOf3, QueryOneOf4, QueryOneOf5, QueryOneOf6, QueryOneOf7, QueryOneOf8, QueryOneOf9. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Query with oneOf schemas: QueryOneOf, QueryOneOf1, QueryOneOf2, QueryOneOf3, QueryOneOf4, QueryOneOf5, QueryOneOf6, QueryOneOf7, QueryOneOf8, QueryOneOf9. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into QueryOneOf
        try:
            instance.actual_instance = QueryOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf1
        try:
            instance.actual_instance = QueryOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf2
        try:
            instance.actual_instance = QueryOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf3
        try:
            instance.actual_instance = QueryOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf4
        try:
            instance.actual_instance = QueryOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf5
        try:
            instance.actual_instance = QueryOneOf5.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf6
        try:
            instance.actual_instance = QueryOneOf6.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf7
        try:
            instance.actual_instance = QueryOneOf7.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf8
        try:
            instance.actual_instance = QueryOneOf8.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into QueryOneOf9
        try:
            instance.actual_instance = QueryOneOf9.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Query with oneOf schemas: QueryOneOf, QueryOneOf1, QueryOneOf2, QueryOneOf3, QueryOneOf4, QueryOneOf5, QueryOneOf6, QueryOneOf7, QueryOneOf8, QueryOneOf9. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Query with oneOf schemas: QueryOneOf, QueryOneOf1, QueryOneOf2, QueryOneOf3, QueryOneOf4, QueryOneOf5, QueryOneOf6, QueryOneOf7, QueryOneOf8, QueryOneOf9. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


