#!/usr/bin/env bash
#
# This file is a quick and dirty workaround for https://github.com/drwetter/testssl.sh/issues/2449#issue-2052861146.
# Its behaves exactly like the original `testssl` but sets the `x` mode for the tempdir.

mktemp() {
        FILE=$(command mktemp "$@");
        if [ -d "$FILE" ]; then
                chmod u+x "$FILE";
        fi;
        echo "$FILE";
}
source testssl "$@";