//! Protobuf declarations and some basic conversions
#![warn(missing_docs, clippy::unwrap_used, clippy::expect_used)]

pub use convert::InvalidArgumentError;
pub use generated::*;

mod convert;

#[allow(clippy::unwrap_used, clippy::expect_used, clippy::large_enum_variant)]
mod generated {

    /// The autogenerated rpc definitions from `attacks.shared.proto`
    pub mod shared {
        tonic::include_proto!("attacks.shared");
    }

    tonic::include_proto!("attacks");
}
