# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.admin_workspaces_api import AdminWorkspacesApi


class TestAdminWorkspacesApi(unittest.TestCase):
    """AdminWorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminWorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_workspaces_admin(self) -> None:
        """Test case for get_all_workspaces_admin

        Retrieve all workspaces
        """
        pass

    def test_get_workspace_admin(self) -> None:
        """Test case for get_workspace_admin

        Retrieve a workspace by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
