# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_invitation(self) -> None:
        """Test case for create_invitation

        Invite a user to the workspace
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create a new workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete a workspace by its id
        """
        pass

    def test_get_all_workspace_invitations(self) -> None:
        """Test case for get_all_workspace_invitations

        Query all open invitations to a workspace
        """
        pass

    def test_get_all_workspaces(self) -> None:
        """Test case for get_all_workspaces

        Retrieve all workspaces that the executing user has access to
        """
        pass

    def test_get_search_results(self) -> None:
        """Test case for get_search_results

        Retrieve results for a search by it's uuid
        """
        pass

    def test_get_searches(self) -> None:
        """Test case for get_searches

        Query all searches
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Retrieve a workspace by id
        """
        pass

    def test_retract_invitation(self) -> None:
        """Test case for retract_invitation

        Retract an invitation to the workspace
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search through a workspaces' data
        """
        pass

    def test_transfer_ownership(self) -> None:
        """Test case for transfer_ownership

        Transfer ownership to another account
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Updates a workspace by its id
        """
        pass


if __name__ == '__main__':
    unittest.main()
