# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.scan_tcp_ports_request import ScanTcpPortsRequest

class TestScanTcpPortsRequest(unittest.TestCase):
    """ScanTcpPortsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScanTcpPortsRequest:
        """Test ScanTcpPortsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScanTcpPortsRequest`
        """
        model = ScanTcpPortsRequest()
        if include_optional:
            return ScanTcpPortsRequest(
                leech_uuid = '',
                targets = ["10.13.37.1","10.13.37.2","10.13.37.0/24"],
                ports = [
                    null
                    ],
                retry_interval = 100,
                max_retries = 2,
                timeout = 3000,
                concurrent_limit = 5000,
                skip_icmp_check = False,
                workspace_uuid = ''
            )
        else:
            return ScanTcpPortsRequest(
                targets = ["10.13.37.1","10.13.37.2","10.13.37.0/24"],
                retry_interval = 100,
                max_retries = 2,
                timeout = 3000,
                concurrent_limit = 5000,
                skip_icmp_check = False,
                workspace_uuid = '',
        )
        """

    def testScanTcpPortsRequest(self):
        """Test ScanTcpPortsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
