# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.ports_api import PortsApi


class TestPortsApi(unittest.TestCase):
    """PortsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PortsApi()

    def tearDown(self) -> None:
        pass

    def test_create_port(self) -> None:
        """Test case for create_port

        Manually add a port
        """
        pass

    def test_get_all_ports(self) -> None:
        """Test case for get_all_ports

        List the ports of a workspace
        """
        pass

    def test_get_port(self) -> None:
        """Test case for get_port

        Retrieve all information about a single port
        """
        pass

    def test_update_port(self) -> None:
        """Test case for update_port

        Update a port
        """
        pass


if __name__ == '__main__':
    unittest.main()
