# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.query_one_of2 import QueryOneOf2

class TestQueryOneOf2(unittest.TestCase):
    """QueryOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryOneOf2:
        """Test QueryOneOf2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryOneOf2`
        """
        model = QueryOneOf2()
        if include_optional:
            return QueryOneOf2(
                username = None
            )
        else:
            return QueryOneOf2(
                username = None,
        )
        """

    def testQueryOneOf2(self):
        """Test QueryOneOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
