# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.ws_message_one_of1 import WsMessageOneOf1

class TestWsMessageOneOf1(unittest.TestCase):
    """WsMessageOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WsMessageOneOf1:
        """Test WsMessageOneOf1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WsMessageOneOf1`
        """
        model = WsMessageOneOf1()
        if include_optional:
            return WsMessageOneOf1(
                invitation_uuid = '',
                workspace = kraken_sdk.models.simple_workspace.SimpleWorkspace(
                    uuid = '', 
                    name = 'ultra-secure-workspace', 
                    description = 'This workspace is ultra secure and should not be looked at!!', 
                    owner = kraken_sdk.models.simple_user.SimpleUser(
                        uuid = '', 
                        username = '', 
                        display_name = '', ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                var_from = kraken_sdk.models.simple_user.SimpleUser(
                    uuid = '', 
                    username = '', 
                    display_name = '', ),
                type = 'InvitationToWorkspace'
            )
        else:
            return WsMessageOneOf1(
                invitation_uuid = '',
                workspace = kraken_sdk.models.simple_workspace.SimpleWorkspace(
                    uuid = '', 
                    name = 'ultra-secure-workspace', 
                    description = 'This workspace is ultra secure and should not be looked at!!', 
                    owner = kraken_sdk.models.simple_user.SimpleUser(
                        uuid = '', 
                        username = '', 
                        display_name = '', ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                var_from = kraken_sdk.models.simple_user.SimpleUser(
                    uuid = '', 
                    username = '', 
                    display_name = '', ),
                type = 'InvitationToWorkspace',
        )
        """

    def testWsMessageOneOf1(self):
        """Test WsMessageOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
