# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.query import Query

class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Query:
        """Test Query
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Query`
        """
        model = Query()
        if include_optional:
            return Query(
                email = None,
                ip_address = None,
                username = None,
                password = None,
                hashed_password = None,
                name = None,
                domain = None,
                vin = None,
                phone = None,
                address = None
            )
        else:
            return Query(
                email = None,
                ip_address = None,
                username = None,
                password = None,
                hashed_password = None,
                name = None,
                domain = None,
                vin = None,
                phone = None,
                address = None,
        )
        """

    def testQuery(self):
        """Test Query"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
