# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.o_auth_api import OAuthApi


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApi()

    def tearDown(self) -> None:
        pass

    def test_accept(self) -> None:
        """Test case for accept

        Endpoint visited by user to grant a requesting application access
        """
        pass

    def test_deny(self) -> None:
        """Test case for deny

        Endpoint visited by user to deny a requesting application access
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Queried by the frontend to display information about the oauth request to the user
        """
        pass


if __name__ == '__main__':
    unittest.main()
