# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.search_type_one_of3 import SearchTypeOneOf3

class TestSearchTypeOneOf3(unittest.TestCase):
    """SearchTypeOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchTypeOneOf3:
        """Test SearchTypeOneOf3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchTypeOneOf3`
        """
        model = SearchTypeOneOf3()
        if include_optional:
            return SearchTypeOneOf3(
                var_or = [
                    null
                    ]
            )
        else:
            return SearchTypeOneOf3(
                var_or = [
                    null
                    ],
        )
        """

    def testSearchTypeOneOf3(self):
        """Test SearchTypeOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
