# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.full_workspace import FullWorkspace

class TestFullWorkspace(unittest.TestCase):
    """FullWorkspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullWorkspace:
        """Test FullWorkspace
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullWorkspace`
        """
        model = FullWorkspace()
        if include_optional:
            return FullWorkspace(
                uuid = '',
                name = 'ultra-secure-workspace',
                description = 'This workspace is ultra secure and should not be looked at!!',
                owner = kraken_sdk.models.simple_user.SimpleUser(
                    uuid = '', 
                    username = '', 
                    display_name = '', ),
                attacks = [
                    kraken_sdk.models.simple_attack.SimpleAttack(
                        uuid = '', 
                        workspace_uuid = '', 
                        attack_type = 'Undefined', 
                        started_by = kraken_sdk.models.simple_user.SimpleUser(
                            uuid = '', 
                            username = '', 
                            display_name = '', ), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                members = [
                    kraken_sdk.models.simple_user.SimpleUser(
                        uuid = '', 
                        username = '', 
                        display_name = '', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FullWorkspace(
                uuid = '',
                name = 'ultra-secure-workspace',
                owner = kraken_sdk.models.simple_user.SimpleUser(
                    uuid = '', 
                    username = '', 
                    display_name = '', ),
                attacks = [
                    kraken_sdk.models.simple_attack.SimpleAttack(
                        uuid = '', 
                        workspace_uuid = '', 
                        attack_type = 'Undefined', 
                        started_by = kraken_sdk.models.simple_user.SimpleUser(
                            uuid = '', 
                            username = '', 
                            display_name = '', ), 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                members = [
                    kraken_sdk.models.simple_user.SimpleUser(
                        uuid = '', 
                        username = '', 
                        display_name = '', )
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFullWorkspace(self):
        """Test FullWorkspace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
