# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.simple_oauth_client import SimpleOauthClient

class TestSimpleOauthClient(unittest.TestCase):
    """SimpleOauthClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimpleOauthClient:
        """Test SimpleOauthClient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimpleOauthClient`
        """
        model = SimpleOauthClient()
        if include_optional:
            return SimpleOauthClient(
                uuid = '',
                name = 'Trustworthy application',
                redirect_uri = 'http://127.0.0.1:8080'
            )
        else:
            return SimpleOauthClient(
                uuid = '',
                name = 'Trustworthy application',
                redirect_uri = 'http://127.0.0.1:8080',
        )
        """

    def testSimpleOauthClient(self):
        """Test SimpleOauthClient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
