# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.wordlist_api import WordlistApi


class TestWordlistApi(unittest.TestCase):
    """WordlistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WordlistApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_wordlists(self) -> None:
        """Test case for get_all_wordlists

        Get a list of all wordlist for the user to select from when starting an bruteforce subdomains attack
        """
        pass


if __name__ == '__main__':
    unittest.main()
