# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.domain_certainty import DomainCertainty

class TestDomainCertainty(unittest.TestCase):
    """DomainCertainty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainCertainty(self):
        """Test DomainCertainty"""
        # inst = DomainCertainty()

if __name__ == '__main__':
    unittest.main()
