# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.dns_resolution_request import DnsResolutionRequest

class TestDnsResolutionRequest(unittest.TestCase):
    """DnsResolutionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsResolutionRequest:
        """Test DnsResolutionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsResolutionRequest`
        """
        model = DnsResolutionRequest()
        if include_optional:
            return DnsResolutionRequest(
                leech_uuid = '',
                targets = ["example.com","example.org"],
                concurrent_limit = 2,
                workspace_uuid = ''
            )
        else:
            return DnsResolutionRequest(
                targets = ["example.com","example.org"],
                concurrent_limit = 2,
                workspace_uuid = '',
        )
        """

    def testDnsResolutionRequest(self):
        """Test DnsResolutionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
