# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.attack_type import AttackType

class TestAttackType(unittest.TestCase):
    """AttackType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttackType(self):
        """Test AttackType"""
        # inst = AttackType()

if __name__ == '__main__':
    unittest.main()
