# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.host_certainty import HostCertainty

class TestHostCertainty(unittest.TestCase):
    """HostCertainty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostCertainty(self):
        """Test HostCertainty"""
        # inst = HostCertainty()

if __name__ == '__main__':
    unittest.main()
