# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.api_keys_api import ApiKeysApi


class TestApiKeysApi(unittest.TestCase):
    """ApiKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key(self) -> None:
        """Test case for create_api_key

        Create new api key
        """
        pass

    def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        Delete an existing api key
        """
        pass

    def test_get_api_keys(self) -> None:
        """Test case for get_api_keys

        Retrieve all api keys
        """
        pass

    def test_update_api_key(self) -> None:
        """Test case for update_api_key

        Update an api key by its id
        """
        pass


if __name__ == '__main__':
    unittest.main()
