# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.get_all_ports_query import GetAllPortsQuery

class TestGetAllPortsQuery(unittest.TestCase):
    """GetAllPortsQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllPortsQuery:
        """Test GetAllPortsQuery
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllPortsQuery`
        """
        model = GetAllPortsQuery()
        if include_optional:
            return GetAllPortsQuery(
                limit = 0,
                offset = 0,
                host = '',
                global_filter = '',
                port_filter = ''
            )
        else:
            return GetAllPortsQuery(
                limit = 0,
                offset = 0,
        )
        """

    def testGetAllPortsQuery(self):
        """Test GetAllPortsQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
