# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.hosts_api import HostsApi


class TestHostsApi(unittest.TestCase):
    """HostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HostsApi()

    def tearDown(self) -> None:
        pass

    def test_create_host(self) -> None:
        """Test case for create_host

        Manually add a host
        """
        pass

    def test_get_all_hosts(self) -> None:
        """Test case for get_all_hosts

        Retrieve all hosts.
        """
        pass

    def test_get_host(self) -> None:
        """Test case for get_host

        Retrieve all information about a single host
        """
        pass

    def test_update_host(self) -> None:
        """Test case for update_host

        Update a host
        """
        pass


if __name__ == '__main__':
    unittest.main()
