# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.o_auth_application_api import OAuthApplicationApi


class TestOAuthApplicationApi(unittest.TestCase):
    """OAuthApplicationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApplicationApi()

    def tearDown(self) -> None:
        pass

    def test_create_oauth_app(self) -> None:
        """Test case for create_oauth_app

        Create a new application
        """
        pass

    def test_delete_oauth_app(self) -> None:
        """Test case for delete_oauth_app

        Delete an application
        """
        pass

    def test_get_all_oauth_apps(self) -> None:
        """Test case for get_all_oauth_apps

        """
        pass

    def test_get_oauth_app(self) -> None:
        """Test case for get_oauth_app

        """
        pass

    def test_update_oauth_app(self) -> None:
        """Test case for update_oauth_app

        Update an application
        """
        pass


if __name__ == '__main__':
    unittest.main()
