# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from kraken_sdk.models.create_host_request import CreateHostRequest

class TestCreateHostRequest(unittest.TestCase):
    """CreateHostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateHostRequest:
        """Test CreateHostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateHostRequest`
        """
        model = CreateHostRequest()
        if include_optional:
            return CreateHostRequest(
                ip_addr = '127.0.0.1',
                certainty = 'Historical'
            )
        else:
            return CreateHostRequest(
                ip_addr = '127.0.0.1',
                certainty = 'Historical',
        )
        """

    def testCreateHostRequest(self):
        """Test CreateHostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
