# coding: utf-8

"""
    kraken

    The core component of kraken-project

    The version of the OpenAPI document: 0.1.0
    Contact: git@omikron.dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kraken_sdk.api.domains_api import DomainsApi


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainsApi()

    def tearDown(self) -> None:
        pass

    def test_create_domain(self) -> None:
        """Test case for create_domain

        Manually add a domain
        """
        pass

    def test_get_all_domains(self) -> None:
        """Test case for get_all_domains

        Retrieve all domains of a specific workspace
        """
        pass

    def test_get_domain(self) -> None:
        """Test case for get_domain

        Retrieve all information about a single domain
        """
        pass

    def test_update_domain(self) -> None:
        """Test case for update_domain

        Update a domain
        """
        pass


if __name__ == '__main__':
    unittest.main()
